// ********RoostGPT********
/*
Test generated by RoostGPT for test Prajwal_Golang using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=ArticleStore_GetTags_45f5cdc4bb
ROOST_METHOD_SIG_HASH=ArticleStore_GetTags_fb0aefcdd2

FUNCTION_DEF=func (s *ArticleStore) GetTags() ([ // GetTags creates a article tag
]model.Tag, error)
Scenario 1: Fetching Tags Successfully When Tags Exist in the Database

Details:
  Description: This test aims to verify the normal operation of the `GetTags` function when tags exist in the database. It ensures that the function returns the correct list of tags without any errors.
Execution:
  Arrange: Prepare mock data containing a list of tags in the database and configure the mock database to simulate a successful query.
  Act: Invoke the `GetTags` method on an instance of `ArticleStore`.
  Assert: Assert that the returned list matches the mock data and error is nil.
Validation:
  Explain the choice of assertion and the logic behind the expected result: This test ensures the function retrieves tags correctly from the database under normal conditions, which is a critical feature for managing article tags.
  Discuss the importance of the test in relation to the application's behavior or business requirements: Tags contribute to classifying and searching articles. Correct functionality ensures that users can look up articles using tags without experiencing application errors.

*/

// ********RoostGPT********

package store

import (
	"runtime/debug"
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/stretchr/testify/assert"
)

func TestArticleStoreGetTags(t *testing.T) {
	type args struct {
		mockTags      []model.Tag
		expectedError error
	}

	tests := []struct {
		name      string
		setupMock func(mock sqlmock.Sqlmock)
		args      args
	}{

		{
			name: "Fetching Tags Successfully When Tags Exist in the Database",
			setupMock: func(mock sqlmock.Sqlmock) {
				rows := sqlmock.NewRows([]string{"id", "name"}).
					AddRow(1, "tag1").
					AddRow(2, "tag2")
				mock.ExpectQuery("^SELECT \\* FROM `tags`$").WillReturnRows(rows)
			},
			args: args{
				mockTags: []model.Tag{
					{ID: 1, Name: "tag1"},
					{ID: 2, Name: "tag2"},
				},
				expectedError: nil,
			},
		},
	}

	defer func() {
		if r := recover(); r != nil {
			t.Logf("Panic encountered so failing test: %v\n%s", r, string(debug.Stack()))
			t.Fail()
		}
	}()

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {

			mockDB, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("An error '%s' was not expected when opening a stub database connection", err)
			}
			defer mockDB.Close()

			gormDB, err := gorm.Open("mysql", mockDB)
			if err != nil {
				t.Fatalf("An error '%s' occurred when creating a GORM DB instance", err)
			}
			defer gormDB.Close()

			store := &ArticleStore{db: gormDB}

			tt.setupMock(mock)

			t.Logf("Calling GetTags method to verify retrieval of tags.")
			tags, err := store.GetTags()

			assert.Equal(t, tt.args.mockTags, tags, "Fetched tags do not match expected tags.")
			assert.Equal(t, tt.args.expectedError, err, "Error returned by GetTags does not match expected error.")

			if err := mock.ExpectationsWereMet(); err != nil {
				t.Errorf("There were unfulfilled mock expectations: %s", err)
			}
		})
	}
}
